raw_data_path: "data/raw/parkinsons_updrs.data"
processed_data_path: "data/processed/parkinsons_cleaned.csv"

# The column used to split train/test (to prevent data leakage)
group_column: "subject#"

# The value we want to predict
target_column: "total_UPDRS" 

# Columns to drop (like the other target 'motor_UPDRS' if we are only predicting total)
drop_columns: ["motor_UPDRS"] 

test_size: 0.2
random_state: 42

